// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SDEVH.Models;

#nullable disable

namespace SDEVH.Migrations
{
    [DbContext(typeof(SdevhContext))]
    [Migration("20240415053345_usuariosregistrohistorial")]
    partial class usuariosregistrohistorial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SDEVH.Models.Usuario", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellidos")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Cargo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Correo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Tel")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("SDEVH.Models.UsuarioHistorial", b =>
                {
                    b.Property<Guid>("IdRegistroUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaRegistroUsuario")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdRegistroUsuario");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioHistorial");
                });

            modelBuilder.Entity("SDEVH.Models.UsuarioHistorial", b =>
                {
                    b.HasOne("SDEVH.Models.Usuario", "RegistradoPorUsuario")
                        .WithMany()
                        .HasForeignKey("IdRegistroUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDEVH.Models.Usuario", null)
                        .WithMany("HistorialUsuariosCollection")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("RegistradoPorUsuario");
                });

            modelBuilder.Entity("SDEVH.Models.Usuario", b =>
                {
                    b.Navigation("HistorialUsuariosCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
